version: "3"
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini
    restart: always

  web:
    image: nginx:latest
    ports:
      - "5000:5500"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    restart: always


volumes:
  socket:
