# Generated by Django 2.2.2 on 2020-06-06 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='limit_to_favorites',
            field=models.BooleanField(default=False, verbose_name='メール通知限定'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='mail_notification',
            field=models.BooleanField(default=False, verbose_name='メール通知'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
