# Generated by Django 2.2.2 on 2021-09-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pole', '0004_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.IntegerField(db_column='blogId', primary_key=True, serialize=False, verbose_name='ブログID')),
                ('date', models.DateTimeField(verbose_name='日時')),
            ],
            options={
                'db_table': 'T_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Girls',
            fields=[
                ('girl_id', models.IntegerField(db_column='girlId', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名前')),
                ('last_update', models.DateTimeField(db_column='lastUpdate', verbose_name='最終更新日')),
            ],
            options={
                'db_table': 'T_girl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GirlsList',
            fields=[
                ('girls_list_id', models.IntegerField(db_column='girlsListId', primary_key=True, serialize=False, verbose_name='GirlsListId')),
                ('blog_id', models.IntegerField(db_column='blogId', verbose_name='ブログID')),
                ('girl_id', models.IntegerField(db_column='girlId', verbose_name='女の子ID')),
            ],
            options={
                'db_table': 'T_girlsList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('image_id', models.IntegerField(db_column='imageId', primary_key=True, serialize=False, verbose_name='imageId')),
                ('file_path', models.CharField(db_column='filePath', max_length=256, verbose_name='ファイルパス')),
            ],
            options={
                'db_table': 'T_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(db_column='blogId', verbose_name='ブログID')),
                ('girl_id', models.IntegerField(db_column='girlId', verbose_name='女の子ID')),
            ],
            options={
                'db_table': 'T_girlsList',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
    ]
