version: '3.1'

services:
  gunicorn:
    image: gunicorn:latest
    build:
      context: .
      dockerfile: dockerfile_gunicorn
    container_name: gunicorn
    command: python /usr/src/app/pole_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - gunicorn:/var/run/gunicorn
    tty: true
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on:
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn

volumes:
  gunicorn:
    driver: local
