version: "3.7"
 
services:
  web:
    build: ./django_project
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - ./static:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - ./static:/home/app/web/static
    ports:
      - 1317:80
    depends_on:
      - web
