version: "3.7"
 
services:
  web:
    build: ./django_project
    command: gunicorn pole_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/usr/src/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/web/static
    ports:
      - 80:80
    depends_on:
      - web
 
volumes:
  static_volume: