FROM python:3.6

COPY ./google-chrome-stable_current_amd64.deb /root
COPY ./chromedriver_linux64.zip /root
copy ./poleScraper-master.zip /root

RUN apt-get update
RUN apt-get install -y less emacs
RUN apt-get install -y git
RUN apt-get install -y unzip

RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

RUN apt-get -y install /root/google-chrome-stable_current_amd64.deb

RUN cd /root
#RUN git clone https://manakamu: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@github.com/manakamu/poleScraper.git
RUN unzip -x /root/poleScraper-master.zip -d /root
RUN mv /root/poleScraper-master/ /root/poleScraper/
RUN unzip -x /root/chromedriver_linux64.zip -d /root

COPY ./run_poleBlogScraper.sh /root/poleScraper/
COPY ./poleBlog.db /root/poleScraper/
RUN chmod +x /root/poleScraper/run_poleBlogScraper.sh
COPY ./config_linux.py /root/poleScraper/

RUN pip install lxml
RUN pip install selenium
RUN pip install requests
RUN pip install cssselect

