FROM python

COPY ./google-chrome-stable_current_amd64.deb /root
COPY ./chromedriver /root


RUN apt-get update
RUN apt-get install -y less emacs
RUN apt-get install -y git

RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9

RUN apt-get -y install /root/google-chrome-stable_current_amd64.deb

RUN cd /root
RUN git clone https://manakamu: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@github.com/manakamu/poleScraper

COPY ./run_poleBlogScraper.sh /root/poleScraper/
COPY ./poleBlog.db /root/poleScraper/
RUN chmod +x /root/poleScraper/run_poleBlogScraper
COPY ./config_linux.py /root/poleScraper/

RUN pip install lxml
RUN pip install selenium
RUN pip install requests
